/* ---------- Toolkit: capability types (no brands) ---------- */
const CAPS = {
  extract:  {name:'Document extraction', one:'Reads documents, emails and forms and pulls out the specific fields you need.',
    good:['Invoices, purchase orders, contracts, claims','Mixed layouts from many senders','Turning free-text requests into structured fields'],
    needs:'Samples of the real documents, and somewhere for the fields to land once extracted.',
    watch:'Confidence varies by field. Route low-confidence items to a person instead of trusting everything.'},
  summarize:{name:'Summarization', one:'Condenses long material into what matters: threads, calls, case histories, reports.',
    good:['Case handover notes','Meeting and call recaps','Digesting many supplier emails at once'],
    needs:'Access to the source material and a clear view of what matters to the reader.',
    watch:'It can flatten nuance. Specify what must never be dropped: dates, amounts, commitments.'},
  retrieve: {name:'Knowledge retrieval & Q&A', one:'Finds the relevant passage in policies, manuals or system records and answers in plain language.',
    good:['Answering questions from a document library','Grounded answers that cite their source','Internal help for staff'],
    needs:'A trustworthy, current set of documents or data to point at.',
    watch:'Stale or contradictory documents produce confident wrong answers. Curate the source first.'},
  vision:   {name:'Computer vision', one:'Interprets images and video: reads labels, counts items, spots defects or damage.',
    good:['Inspection and quality checks','Reading labels, meters, plates','Counting stock or verifying a packed order'],
    needs:'Consistent images and labelled examples of what to detect.',
    watch:'Lighting, angle and camera quality make or break it. Pilot in the real environment.'},
  speech:   {name:'Speech & voice', one:'Turns speech into text and back: transcribes calls, captures notes, powers voice interfaces.',
    good:['Call transcription and after-call notes','Hands-free capture in the field','Voice-based ordering or lookup'],
    needs:'Decent audio and consent to record.',
    watch:'Accents, jargon and background noise reduce accuracy. Pair with a review step for anything binding.'},
  classify: {name:'Classification & routing', one:'Sorts items into categories: intents, priorities, teams, risk levels.',
    good:['Triaging inboxes and tickets','Tagging cases by type or urgency','Sending work to the right queue'],
    needs:'Clear categories and examples of items in each.',
    watch:'Ambiguous items need an "unsure" bucket. Measure misroutes, not just speed.'},
  anomaly:  {name:'Anomaly & error detection', one:'Flags items that do not look like the rest: duplicates, unusual amounts, suspicious changes.',
    good:['Duplicate or fraudulent payments','Data-entry errors','Unusual demand spikes'],
    needs:'A baseline of normal, and a person to investigate what gets flagged.',
    watch:'Tune the threshold. Too many flags and people stop looking.'},
  predict:  {name:'Prediction & forecasting', one:'Estimates a number or likelihood from historical patterns: demand, churn, lead time, risk.',
    good:['Demand and volume forecasts','Likelihood scores (churn, late payment)','Estimating durations and costs'],
    needs:'Enough history at the right granularity, including the outcomes you want to predict.',
    watch:'Patterns shift. Monitor accuracy and let planners override with a reason.'},
  recommend:{name:'Recommendation & decision support', one:'Ranks options and surfaces the evidence so a person decides faster and more consistently.',
    good:['Suggesting substitutes or next steps','Prioritising a work queue','Showing the policy, history and precedent for a judgment call'],
    needs:'Outcome data or clear criteria for what good looks like.',
    watch:'Keep the person accountable for the decision. Log why suggestions were overridden.'},
  optimize: {name:'Optimization & scheduling', one:'Finds the best plan under constraints: routes, schedules, stock allocation, staffing.',
    good:['Delivery routing','Order quantities across warehouses','Shift and job scheduling'],
    needs:'Explicit constraints and a clear objective: cost, time or service level.',
    watch:'Real life has unstated constraints. Let planners edit the plan and feed the reasons back.'},
  draft:    {name:'Drafting & generation', one:'Writes a first version: emails, descriptions, reports, documents from a template.',
    good:['Replies that follow a pattern','Product descriptions, job posts, briefs','Turning bullet notes into prose'],
    needs:'Examples of good output and the facts to include.',
    watch:'Drafts, not decisions. Someone accountable reviews anything sent outside.'},
  converse: {name:'Conversational assistant', one:'A natural-language front door for customers or staff, answering and acting within set limits.',
    good:['Self-service for common questions','Guided intake ("what do you need?")','Internal assistants over policy and systems'],
    needs:'A well-defined scope, connected data, and a graceful handoff to a person.',
    watch:'Only as good as what it is connected to. A chatbot over bad documentation is a faster way to be wrong.'},
  agent:    {name:'Agentic workflow automation', one:'Carries out multi-step tasks across systems: looks things up, fills forms, sends messages, escalates.',
    good:['Chasing and coordinating routine follow-ups','Multi-system tasks with variable inputs','Preparing a case so a person only approves'],
    needs:'System access, clear stopping rules, and a log of every action taken.',
    watch:'Errors compound across steps. Start with "propose, then a person approves" before letting it act alone.'},
  rules:    {name:'Rules-based automation (no AI)', one:'If the logic can be written down as rules, a workflow tool or your existing system does it reliably and cheaply.',
    good:['Three-way matching','Generating standard documents','Threshold approvals and reminders'],
    needs:'Stable rules and structured data.',
    watch:'Do not reach for AI when a rule will do. Do not force rules on work that is truly variable.'},
  fix:      {name:'Fix the process (no tool)', one:'Sometimes the step only exists because of a broken handoff, a missing field or a bad form. Remove the cause.',
    good:['Removing rework loops','Capturing data at the source','Self-service instead of handling requests'],
    needs:'Permission to change the process, and the upstream owner in the room.',
    watch:'Automating a broken process makes it break faster.'},
};

const CAP_FAMILIES = [
  {id:'read',  name:'Read & understand',      caps:['extract','summarize','retrieve','vision','speech']},
  {id:'judge', name:'Sort, predict & decide',  caps:['classify','anomaly','predict','recommend','optimize']},
  {id:'act',   name:'Create & act',            caps:['draft','converse','agent']},
  {id:'none',  name:'Not an AI problem',       caps:['rules','fix']},
];

/* ---------- Anatomy of a task: the four dimensions ---------- */
const SHAPES = [
  {id:'extract',   name:'Read & pull out facts',      d:'Take documents or messages and get the specific details out of them.'},
  {id:'route',     name:'Sort, tag & route',          d:'Decide which bucket, queue or person each item goes to.'},
  {id:'lookup',    name:'Look up & answer',           d:'Find information that already exists and respond to a question.'},
  {id:'draft',     name:'Write & draft',              d:'Produce text: replies, descriptions, documents.'},
  {id:'summarize', name:'Condense & summarize',       d:'Turn a lot of material into the few things that matter.'},
  {id:'predict',   name:'Estimate & forecast',        d:'Put a number or likelihood on something that has not happened yet.'},
  {id:'check',     name:'Check & flag',               d:'Compare against what is expected and flag what is off.'},
  {id:'suggest',   name:'Suggest & rank options',     d:'Propose the best next step, item or action from many possibilities.'},
  {id:'allocate',  name:'Allocate & schedule',        d:'Fit many things into limited capacity under constraints.'},
  {id:'decide',    name:'Judge & decide',             d:'Weigh a situation and make a call someone is accountable for.'},
  {id:'coordinate',name:'Chase, coordinate & update', d:'Follow up with people and move information between systems.'},
  {id:'physical',  name:'Handle or inspect physically',d:'Move, pack, count or examine real things.'},
];
const INPUTS = [
  {id:'structured', name:'Structured data',       d:'Fields, tables, system records.'},
  {id:'text',       name:'Unstructured text',     d:'Emails, PDFs, notes, chat.'},
  {id:'media',      name:'Images, audio or video', d:'Photos, scans that are really pictures, recordings, calls.'},
  {id:'tacit',      name:'Not captured anywhere', d:'In people\u2019s heads, on calls nobody records.'},
];
const REPS = [
  {id:'high', name:'High',   d:'Many times a day, similar each time.'},
  {id:'mid',  name:'Medium', d:'Regular, but each one varies.'},
  {id:'low',  name:'Low',    d:'Rare or one-off.'},
];
const STAKES = [
  {id:'low',  name:'Low',    d:'Clear rules; an error is cheap to fix.'},
  {id:'mid',  name:'Medium', d:'Some judgment; errors cost time or money.'},
  {id:'high', name:'High',   d:'Nuanced judgment; regulated or costly errors.'},
];
const AUTONOMY = [
  {id:'assist', name:'Assist',               d:'AI prepares; a person decides every case.'},
  {id:'review', name:'Automate with review', d:'AI handles the routine; people see the exceptions.'},
  {id:'auto',   name:'Fully automate',       d:'AI acts; people watch the metrics.'},
];
const LEVELS = [
  {id:'low', name:'Low'},{id:'mid', name:'Medium'},{id:'high', name:'High'},
];
const DIMS = [
  {id:'shape',  label:'Shape of the work',      q:'What is the person actually doing?',                 opts:SHAPES},
  {id:'input',  label:'Inputs',                 q:'What does the work start from?',                     opts:INPUTS},
  {id:'rep',    label:'Volume & repetition',    q:'How often, and how similar each time?',              opts:REPS},
  {id:'stakes', label:'Judgment & stakes',      q:'How much judgment, and what does an error cost?',    opts:STAKES},
];

const GUARDRAILS = [
  {id:'threshold', name:'Confidence threshold',     d:'Low-confidence items go to a person.'},
  {id:'logging',   name:'Log every action',         d:'Each decision or action is recorded and reviewable.'},
  {id:'privacy',   name:'Personal data per policy', d:'Minimum data, right storage, access controls.'},
  {id:'escalation',name:'Clear path to a person',   d:'Anyone can hand off or appeal to a human quickly.'},
  {id:'rollback',  name:'Rollback plan',            d:'The manual process can resume within a day.'},
  {id:'sampling',  name:'Accuracy sampling',        d:'Regularly check outputs against ground truth.'},
  {id:'bias',      name:'Fairness review',          d:'Check outcomes across groups when people are affected.'},
];

/* ---------- The fictional institution ---------- */
const COMPANY = {
  name:'Meridian Reserve Bank',
  blurb:'A district reserve bank: 2,400 people across a headquarters and two branch buildings. Its economists and researchers feed the analysis behind the national interest-rate decision. Everyone else keeps three secure buildings, their systems and their people running. Careful, credible, and run on inherited systems, shared inboxes and institutional memory.',
  role:'You have been asked to lead the search for where AI could help the Bank. The president wants a shortlist for the next leadership meeting. Nobody has yet asked which processes need help first, or what the Bank can afford to get wrong. That is your job.',
};

const MAP_GROUPS = [
  {id:'mission',   label:'The mission',              d:'The analysis behind the rate decision.'},
  {id:'buildings', label:'Running the buildings',    d:'Three secure sites, kept open and safe.'},
  {id:'people',    label:'Supporting the people',    d:'Systems, careers and benefits for 2,400 staff.'},
];

const FUNCTIONS = [
  {id:'econ', name:'Economists', group:'mission', icon:'econ',
   brief:'48 economists and analysts turn data releases, market moves and district intelligence into the briefings behind eight rate-setting meetings a year.',
   signals:[{t:'The pre-meeting briefing book takes three weeks and 30 people to assemble. Two thirds of that is gathering and formatting, not analysis.', s:'strong'},{t:'District business contacts are interviewed by phone and summarised from memory.', s:'medium'}],
   processes:[
    {id:'briefing', name:'Pre-meeting briefing cycle', d:'Gather data, update models and charts, write and check the briefing memo, prepare the president\u2019s Q&A.', rating:5, authored:'A', why:'A high volume of repeatable gathering, formatting and checking around a small core of expert judgment, on a fixed calendar, with a measurable cost in economist hours. The judgment stays human; everything around it is a hotspot.'},
    {id:'beigebook', name:'District business intelligence', d:'Interview business contacts, summarise, and roll up into the district report.', rating:4, why:'Recurring, transcribable and summarisable, and currently done from memory. A strong second candidate in assist mode.'},
    {id:'ratevote', name:'The policy recommendation itself', d:'Form the president\u2019s view for the rate-setting meeting.', rating:1, why:'Eight times a year, the highest judgment in the building. Not a process to automate; the job is to feed it better.'},
   ]},
  {id:'research', name:'Researchers', group:'mission', icon:'research',
   brief:'60 researchers produce working papers, maintain data sets and answer data requests from across the Bank and from the public.',
   signals:[{t:'Researchers spend about 40% of their time on data cleaning and literature review before any analysis starts.', s:'strong'},{t:'1,100 external data requests a year, most answered by hand.', s:'medium'}],
   processes:[
    {id:'datacleaning', name:'Data set maintenance & cleaning', d:'Ingest, clean, document and refresh the Bank\u2019s research data sets.', rating:4, why:'Repetitive, rule-heavy, and measurably expensive at 40% of researcher time. Anomaly detection and plain rules do a great deal here.'},
    {id:'litreview', name:'Literature search & review', d:'Find and digest the published work relevant to a question.', rating:3, why:'Retrieval and summarisation over published work is a natural assist. Volume is real but spread thin across many topics, and each paper still needs an expert reader.'},
    {id:'datareq', name:'External data requests', d:'Answer requests for series, methods and publications.', rating:3, why:'Recurring and mostly answered from published series. Self-service and retrieval remove much of it; the remainder needs a researcher.'},
   ]},
  {id:'facilities', name:'Building & facilities operations', group:'buildings', icon:'facilities',
   brief:'210 people run three buildings: 1.4 million square feet, a vault, two data halls, a central plant, and 9,000 work orders a year.',
   signals:[{t:'9,000 work orders a year arrive by email, phone and a web form. Two coordinators dispatch them from a shared inbox.', s:'strong'},{t:'Preventive maintenance is planned in a spreadsheet; 18% of critical equipment is overdue.', s:'strong'}],
   processes:[
    {id:'workorders', name:'Maintenance work orders', d:'Receive, triage, assign, schedule and close maintenance work across three buildings.', rating:5, authored:'B', why:'High volume, repetitive intake and dispatch, a measured backlog, and inputs that already arrive digitally. A classic operations hotspot.'},
    {id:'energy', name:'Energy & central plant management', d:'Run the chillers, boilers and power systems efficiently.', rating:3, why:'Sensor data exists and optimisation pays, but the plant already runs on a specialist vendor system. The opportunity is narrower than it looks.'},
    {id:'spaceplan', name:'Space & occupancy planning', d:'Decide who sits where and what to renovate.', rating:2, why:'A few large decisions a year with committee sign-off. Analytics help; there is no volume to automate.'},
   ]},
  {id:'events', name:'Events coordination', group:'buildings', icon:'events',
   brief:'Three event teams, 14 people in all, run about 1,900 meetings and events a year across the buildings, from board meetings to public tours.',
   signals:[{t:'Every request needs a room, AV, catering and security clearance coordinated across four systems.', s:'medium'},{t:'Attendee lists arrive in whatever format the host sends.', s:'weak'}],
   processes:[
    {id:'eventreq', name:'Event requests & coordination', d:'Take a request, book the room and AV, arrange catering, clear attendees with security.', rating:4, why:'Recurring multi-system coordination with variable inputs. Agentic automation and rules do well here, and the volume justifies it.'},
    {id:'tours', name:'Public tours & visitor programme', d:'Schedule and run tours for schools and the public.', rating:2, why:'Seasonal and modest. A booking form and a rule handle most of it.'},
   ]},
  {id:'police', name:'Law enforcement', group:'buildings', icon:'police',
   brief:'A sworn law-enforcement unit at each building: 190 officers screening 380,000 visitors and deliveries a year, monitoring 2,600 cameras and responding to incidents.',
   signals:[{t:'Visitor pre-registration arrives by email from 900 different hosts. Officers re-key it at the desk.', s:'strong'},{t:'Incident reports are typed after shift from notes. Review takes a supervisor two hours a day per building.', s:'medium'}],
   processes:[
    {id:'screening', name:'Visitor & delivery screening', d:'Register, identify, check and clear every person and package entering the buildings.', rating:5, authored:'D', why:'Very high volume, repetitive checks with clear rules, digital inputs and a measurable queue at the door. High stakes at the edges, which is exactly what the autonomy dial is for.'},
    {id:'incidents', name:'Incident reporting & review', d:'Write up incidents and review them for classification and escalation.', rating:4, why:'Daily, text-heavy, and reviewed by hand. Drafting from notes, classification and summarisation help; judgment stays with supervisors.'},
    {id:'shifts', name:'Patrol & shift scheduling', d:'Roster 190 officers across posts, shifts and three buildings.', rating:3, why:'A constrained scheduling problem with written rules. Optimisation fits; the volume is moderate.'},
   ]},
  {id:'it', name:'Enterprise IT', group:'people', icon:'it',
   brief:'260 people support every system in the Bank, from market-data feeds to 2,400 laptops, with 3,100 helpdesk tickets a month.',
   signals:[{t:'38% of tickets are password resets and access requests.', s:'strong'},{t:'Access reviews for 400 applications are done by spreadsheet twice a year.', s:'medium'}],
   processes:[
    {id:'helpdesk', name:'Helpdesk ticket handling', d:'Triage, resolve or escalate requests for help.', rating:4, why:'High volume and repetitive. The biggest slice is a rules and self-service fix; classification and retrieval handle the rest.'},
    {id:'accessreview', name:'Access reviews & provisioning', d:'Grant, review and remove access to systems.', rating:3, why:'Twice-yearly bulk work with real risk attached. Rules and anomaly detection over entitlements do most of it; approvals stay human.'},
    {id:'roadmap', name:'Technology roadmap', d:'Decide the next three years of systems investment.', rating:1, why:'Annual, strategic and judgment-heavy. Not a process to automate.'},
   ]},
  {id:'hr', name:'Human resources', group:'people', icon:'hr',
   brief:'55 people hire, develop and support 2,400 employees, filling around 220 roles a year under public-sector hiring rules.',
   signals:[{t:'Time to hire is 74 days; the screening stage alone takes three weeks.', s:'medium'},{t:'Managers ask HR the same policy questions repeatedly: 1,400 tickets a quarter.', s:'medium'}],
   processes:[
    {id:'policyq', name:'Employee policy questions', d:'Answer questions about leave, travel, conduct and pay policy.', rating:4, why:'Repetitive, low stakes, and the answers already exist in policy documents. Retrieval and Q&A over the policy library is a natural fit.'},
    {id:'recruit', name:'Recruiting & candidate screening', d:'Post roles, screen applicants, interview, select.', rating:2, why:'Decisions about people are high stakes and, for a public institution, closely scrutinised. Assist mode later; not a first expedition.'},
    {id:'perf', name:'Performance review cycle', d:'Set goals, gather feedback, write and calibrate reviews.', rating:2, why:'Annual and judgment-heavy. Drafting help for managers is possible; the value is modest and the sensitivity high.'},
   ]},
  {id:'benefits', name:'Benefits organization', group:'people', icon:'benefits',
   brief:'32 people administer health, retirement and leave benefits for 2,400 employees and 3,800 retirees, and run open enrolment every autumn.',
   signals:[{t:'Open enrolment generates 6,000 questions in five weeks. The same forty questions make up most of them.', s:'strong'},{t:'Eligibility documents are checked by hand: 9,000 a year, eleven days average turnaround.', s:'strong'}],
   processes:[
    {id:'benefitsq', name:'Benefits inquiries & enrolment', d:'Answer questions, verify documents, process elections, administer leave, reconcile carriers.', rating:5, authored:'C', why:'Very high seasonal volume, a small set of repeated questions, documents to read and rules to check, with measurable turnaround pain. A hotspot with a privacy dimension.'},
    {id:'retiree', name:'Retiree pension changes', d:'Process address, beneficiary and payment changes for retirees.', rating:3, why:'Steady, document-based and rule-bound. Smaller than enrolment, with an older population that needs a human path.'},
    {id:'vendorrecon', name:'Carrier invoice reconciliation', d:'Match insurance carrier bills to enrolment records.', rating:3, why:'Monthly matching of bills to records. Mostly rules and anomaly detection.'},
   ]},
];

/* ---------- Four processes with full field access ---------- */
const PROCESSES = {
 A:{ id:'A', name:'Pre-meeting briefing cycle', fn:'Economists', fnId:'econ',
  intro:'Eight times a year, 48 economists assemble the briefing book the president reads before the rate-setting meeting: data, charts, models, memos and the questions likely to be asked. Three weeks, thirty people, and one decision nobody will automate. Walk the cycle.',
  steps:[
   {id:'A1', name:'Gather data releases and market moves', who:'Analysts', volume:'90 releases and 40 market series per cycle', systems:'Agency websites, market data terminal, series database',
    notes:'In the week before drafting starts, analysts pull every scheduled data release, revision and market move into the Bank\u2019s series database and a set of standard charts. Most releases arrive as PDFs and web tables in the agency\u2019s own layout. Revisions to earlier months have to be caught by hand.',
    pain:'Two analyst-weeks per cycle on collection and formatting. A missed revision last year had to be corrected on the day of the meeting.',
    expert:{shape:'extract', shapeAlt:['check'], input:'text', inputAlt:['structured'], rep:'high', repAlt:[], stakes:'mid', stakesAlt:['high']},
    profileNotes:{shape:'Pulling numbers out of releases and into the database is extraction. Catching revisions is a check, and it belongs to the same work.', input:'Agency PDFs and web tables: unstructured, even when the numbers inside are tidy.', rep:'Ninety releases a cycle, eight cycles a year, similar every time.', stakes:'A wrong number in the briefing book is serious but caught by later review: medium, leaning high.'},
    fit:{best:['extract'], ok:['rules','anomaly','agent']},
    fitNotes:{extract:'Reading releases in many layouts into structured series is extraction, and it can flag where a number changed from the last vintage.', rules:'Workable for the agencies that publish machine-readable feeds. Many still do not.', anomaly:'Workable as the companion: flag revisions and implausible values for an analyst to check.', agent:'Workable later: fetch, extract, load and flag on the release calendar, with an analyst confirming.', draft:'Nothing is being written at this step.', predict:'You are collecting what happened, not estimating what will.'},
    poorNote:'This step turns published documents into numbers in a database. Pick the capability that reads.',
    expertPick:'extract', expertWhy:'Extraction from releases into the series database with revision flags, run on the release calendar. Analysts confirm the flagged values and spend the saved week on analysis.',
    autoBest:'review', autoOk:['auto'], autoNote:'Medium stakes and structured outcomes: load automatically, review what is flagged. Full automation is reasonable for machine-readable feeds.',
    discoveries:[{title:'Feeds for half', text:'About half the agencies already publish machine-readable feeds. The Bank pulls PDFs from them anyway, out of habit.', effect:'Fix first: switch to the feeds, then extract only what needs extracting.'},{title:'Revisions are the risk', text:'Revisions to prior months are where the errors have come from. The current process has no systematic check.', effect:'The anomaly flag is the part that prevents the next correction.'}],
    expertFeas:'high', expertValue:'mid', realityNote:'Very doable, and half of it is a habit change. Medium value on its own, and it feeds everything downstream.',
    metric:'Analyst hours per cycle on collection, and revisions caught before drafting', guardrails:['threshold','sampling','logging'],
    valueHyp:'Return two analyst-weeks per cycle and catch every revision before the memo is drafted.',
    dataNeeded:'The release calendar, past releases alongside the series they were loaded into, and agency feed access.'},
   {id:'A2', name:'Update the nowcast and short-term forecasts', who:'Forecasting team', volume:'12 core models, weekly through the cycle', systems:'Model code, series database, adjustment spreadsheet',
    notes:'A small team re-runs the Bank\u2019s nowcast and short-term forecasts as new data arrives, then adjusts by judgment for what the models cannot see: a strike, a storm, a policy announcement. The judgmental adjustments are recorded in a spreadsheet with a one-line reason.',
    pain:'Each re-run takes a day. The reasons behind past adjustments are hard to reconstruct.',
    expert:{shape:'predict', shapeAlt:[], input:'structured', inputAlt:[], rep:'mid', repAlt:['high'], stakes:'high', stakesAlt:['mid']},
    profileNotes:{shape:'Putting numbers on next quarter: estimate and forecast, with judgment layered on top.', input:'Series in the database: structured.', rep:'Weekly through the cycle, but each run is a considered exercise.', stakes:'The forecasts frame the president\u2019s view. High.'},
    fit:{best:['predict'], ok:['anomaly','summarize','rules']},
    fitNotes:{predict:'Modern forecasting methods can run alongside the Bank\u2019s models as a check and speed the re-runs. They do not replace the economists\u2019 judgment layer.', anomaly:'Workable: flag when incoming data breaks from the model\u2019s expectation, which is exactly when judgment is needed.', summarize:'Workable for the adjustment log: a narrative of what was adjusted and why, assembled automatically.', rules:'Automating the re-run pipeline is plain engineering and worth doing. It is not the AI part.', draft:'The memo comes later.', converse:'Nobody needs to chat with the nowcast.'},
    poorNote:'This step is estimation with expert judgment on top. Pick the capability that estimates, and keep the judgment.',
    expertPick:'predict', expertWhy:'Automated re-runs, a competing forecast as a sanity check, and a structured adjustment log. Economists keep the judgment and gain the time and the audit trail.',
    autoBest:'assist', autoOk:['review'], autoNote:'High stakes: the models propose, economists decide every number that reaches the president. Automate the plumbing, never the judgment.',
    discoveries:[{title:'Adjustment memory', text:'The judgmental adjustments live in a spreadsheet with one-line reasons. The last three years cannot be reconstructed.', effect:'Capture the reasoning properly first. It is also the data a future model would learn from.'},{title:'Compute is not the problem', text:'The re-run pipeline is slow because it is run by hand across four machines, not because the models are heavy.', effect:'Feasibility: engineering, not research.'}],
    expertFeas:'mid', expertValue:'mid', realityNote:'Sensible and bounded. Medium on both axes: the win is time and traceability, not a better number.',
    metric:'Hours per re-run, and adjustments with a recorded rationale', guardrails:['logging','sampling','escalation'],
    valueHyp:'Cut a re-run from a day to an hour and make every adjustment traceable.',
    dataNeeded:'Series database, model code, and the adjustment log with reasons.'},
   {id:'A3', name:'Draft the briefing memo', who:'Senior economists', volume:'14 memos per cycle, 8 to 20 pages each', systems:'Word processor, chart library, shared drive',
    notes:'Each section owner writes a memo: what happened, what it means, what to watch. The first third of every memo describes data the charts already show. Drafts go through three rounds of comments before the president sees them.',
    pain:'Senior economists spend a week per cycle writing description the charts already carry, before they reach the analysis they are paid for.',
    expert:{shape:'draft', shapeAlt:['summarize'], input:'structured', inputAlt:['text'], rep:'mid', repAlt:[], stakes:'high', stakesAlt:[]},
    profileNotes:{shape:'Writing prose from data and charts: draft, with summarising underneath.', input:'Charts and series (structured) plus the previous memo (text).', rep:'Fourteen memos a cycle, different in content, similar in form.', stakes:'This is the document the decision rests on: high.'},
    fit:{best:['draft'], ok:['summarize','retrieve']},
    fitNotes:{draft:'Drafting the descriptive first third from the data and the chart set, in house style, leaves the economist writing the analysis.', summarize:'Workable: a summary of what changed since the last memo is most of the descriptive section.', retrieve:'Workable: pull the relevant passages from past memos and the sources the section usually cites.', agent:'The memo is not a multi-system task. It is writing.', converse:'Nobody wants to chat their way to a briefing memo.', rules:'Templates already exist. The words still have to be written.'},
    poorNote:'This step is writing, with judgment. Pick the capability that drafts, and keep the author.',
    expertPick:'draft', expertWhy:'A grounded first draft of the descriptive sections from the data, in house style, with every number linked to its series. The economist writes the analysis and owns the whole memo.',
    autoBest:'assist', autoOk:[], autoNote:'High stakes: the economist edits and owns every word. Nothing here goes forward without an author.',
    discoveries:[{title:'The sensitive document', text:'The briefing book is among the most sensitive documents the Bank produces. It cannot touch any service outside the Bank\u2019s approved environment.', effect:'Risk: any tool must run inside the approved boundary. Non-negotiable.'},{title:'Style is codified', text:'The Bank has a written style guide and fifteen years of past memos.', effect:'Data: excellent examples of good output exist.'}],
    expertFeas:'mid', expertValue:'high', realityNote:'High value, and the examples exist. Feasibility hinges on running inside the Bank\u2019s boundary, which makes it a strategic bet.',
    metric:'Senior economist hours per memo, and factual corrections found in review', guardrails:['privacy','logging','sampling'],
    valueHyp:'Give senior economists back half their drafting week for analysis.',
    dataNeeded:'Series and chart library, past memos, the style guide, and an approved internal model environment.'},
   {id:'A4', name:'Fact-check and cross-reference the book', who:'Review editors', volume:'About 400 pages per cycle', systems:'Manuscripts, series database',
    notes:'Two editors check every number in the book against the database and every chart against its data, and make sure the sections do not contradict each other. It takes four days, and something is always found.',
    pain:'Four days on the critical path, and human eyes tire by page 300.',
    expert:{shape:'check', shapeAlt:[], input:'text', inputAlt:['structured'], rep:'mid', repAlt:['high'], stakes:'high', stakesAlt:[]},
    profileNotes:{shape:'Comparing what is written against what is true: check and flag.', input:'Manuscripts (text) checked against the database (structured).', rep:'Four hundred pages a cycle, page after page.', stakes:'An error in the book reaches the president: high.'},
    fit:{best:['anomaly','extract'], ok:['rules','retrieve']},
    fitNotes:{anomaly:'Flag numbers in the text that do not match the database, charts that do not match their series, and statements that contradict another section.', extract:'Pulling every number and claim out of the manuscript is the first half of the check.', rules:'Workable where numbers are linked to their series; it catches the mechanical mismatches only.', retrieve:'Workable for checking a claim against the memo it cites.', draft:'Nothing to write.', predict:'Nothing to forecast.'},
    poorNote:'This step compares text against truth. Pick the capability that finds what does not match.',
    expertPick:'anomaly', expertWhy:'Extract every figure and claim, compare against the database and the other sections, and hand the editors a ranked list of discrepancies. The editors still read the book; they read it with a map.',
    autoBest:'assist', autoOk:['review'], autoNote:'High stakes: the tool points, the editors decide. It shortens the four days; it does not replace the reading.',
    discoveries:[{title:'Numbers are not linked', text:'Figures in the memos are typed, not linked to the database. The tool has to find them first.', effect:'Change: link numbers at the source and the check gets much easier.'},{title:'The contradictions', text:'The costly errors have been contradictions between sections, not typos.', effect:'The cross-reference is the valuable part.'}],
    expertFeas:'mid', expertValue:'high', realityNote:'High value on the critical path. Medium feasibility until numbers are linked at the source.',
    metric:'Review days per cycle, and errors found after publication', guardrails:['logging','sampling','escalation'],
    valueHyp:'Cut review from four days to two and catch the contradictions the eye misses.',
    dataNeeded:'Manuscripts, the series database, and past review corrections.'},
   {id:'A5', name:'Prepare the president\u2019s Q&A', who:'President\u2019s staff and section chiefs', volume:'About 150 anticipated questions per cycle', systems:'Transcript archive, memo archive, media digest',
    notes:'Staff anticipate what the president may be asked at the meeting and at the press conference after it: what colleagues argued last time, what journalists have written, where the data is ambiguous. They draft questions and suggested answers, and the president rehearses.',
    pain:'A week of senior time re-reading transcripts and clippings. The same ground is covered each cycle.',
    expert:{shape:'lookup', shapeAlt:['summarize'], input:'text', inputAlt:[], rep:'mid', repAlt:[], stakes:'high', stakesAlt:['mid']},
    profileNotes:{shape:'Finding what was said, asked and written, and bringing it together: look up and answer, with summarising.', input:'Transcripts, memos and articles: text.', rep:'Each cycle, on the same pattern.', stakes:'The president\u2019s public words move markets: high.'},
    fit:{best:['retrieve','summarize'], ok:['draft','classify']},
    fitNotes:{retrieve:'Retrieval over transcripts, memos and coverage surfaces what was asked before, how it was answered, and what changed.', summarize:'A digest of press and market commentary since the last meeting is most of the preparation.', draft:'Workable for suggested answers, as drafts the staff rewrite.', classify:'Workable for sorting the commentary into themes.', agent:'Nothing to coordinate.', predict:'You cannot forecast a question. You can prepare for the likely ones.'},
    poorNote:'This step assembles what is already known. Pick the capability that finds and condenses.',
    expertPick:'retrieve', expertWhy:'Retrieval over the archive and a themed digest of commentary, producing a draft question bank with sources. Staff refine it; the president rehearses with humans.',
    autoBest:'assist', autoOk:[], autoNote:'High stakes: everything is a draft for staff. No answer goes near the president without a person behind it.',
    discoveries:[{title:'Archive in good shape', text:'Transcripts and memos are well archived and searchable inside the Bank.', effect:'Data: ready.'},{title:'Outside coverage, outside the wall', text:'Media monitoring comes from an external service. Combining it with internal documents raises the boundary question again.', effect:'Risk: bring the external digest inside, never internal documents out.'}],
    expertFeas:'high', expertValue:'mid', realityNote:'Feasible now with the internal archive. Medium value: it saves senior time and improves consistency, but the president was already well prepared.',
    metric:'Senior hours per cycle on preparation, and questions asked that were not anticipated', guardrails:['privacy','logging','sampling'],
    valueHyp:'Halve preparation time and widen the range of questions anticipated.',
    dataNeeded:'The transcript and memo archive, and the media digest.'},
  ]},
 B:{ id:'B', name:'Maintenance work orders', fn:'Building & facilities operations', fnId:'facilities',
  intro:'Nine thousand requests a year for three buildings: a cold office, a flickering light in the vault corridor, a chiller alarm at three in the morning. Two coordinators sort them from a shared inbox; forty technicians and a dozen vendors do the work. Walk the process.',
  steps:[
   {id:'B1', name:'Receive and triage requests', who:'2 dispatch coordinators', volume:'About 40 requests a day', systems:'Shared inbox, web form, phone log, ticketing',
    notes:'Requests arrive by email, a web form and phone. The coordinators read each one, decide the trade (electrical, HVAC, plumbing, locks, cleaning), the priority and the building, and create a ticket. On a busy morning, urgent items wait behind routine ones.',
    pain:'Two people spend their day sorting. Urgent requests are found late about once a week.',
    expert:{shape:'route', shapeAlt:[], input:'text', inputAlt:[], rep:'high', repAlt:[], stakes:'low', stakesAlt:['mid']},
    profileNotes:{shape:'Deciding trade, priority and building for each request: sort and route.', input:'Emails and form text: unstructured.', rep:'Forty a day, most alike.', stakes:'A misrouted ticket costs an hour; a missed urgent one costs more. Low, leaning medium.'},
    fit:{best:['classify'], ok:['rules','agent','fix']},
    fitNotes:{classify:'Trade, priority and building from a free-text request is classification, and it handles phrasing that rules miss.', rules:'Workable for the web form, if the form asks the right questions. Email and phone need more.', agent:'Workable: classify, create the ticket, notify the technician. Prove the classification first.', fix:'Half the emails would be form submissions if the form were easier to find. Fix that and there is less to sort.', converse:'A conversational intake could work; the form is the simpler first move.', extract:'Close: pulling the location and asset out of the request is part of it, but the decision is the routing.'},
    poorNote:'This step sorts requests into the right queue. Pick the capability that sorts.',
    expertPick:'classify', expertWhy:'Classification with a confidence threshold, urgent items flagged to a person immediately, and a better form to shrink the pile. The coordinators become the escalation point.',
    autoBest:'review', autoOk:['auto'], autoNote:'Low to medium stakes: route the confident ones automatically, send the unsure and the urgent to a coordinator.',
    discoveries:[{title:'Three years of labelled tickets', text:'Every past ticket carries the trade and priority the coordinators assigned.', effect:'Data: excellent training examples already exist.'},{title:'The form nobody finds', text:'The web form is four clicks deep on the intranet. Most people email instead.', effect:'Fix first: surface the form and half the sorting disappears.'}],
    expertFeas:'high', expertValue:'mid', realityNote:'Quick win: labelled data, simple integration, and a process fix that pays immediately.',
    metric:'Minutes from request to ticket, and urgent requests found late', guardrails:['threshold','escalation','sampling'],
    valueHyp:'Free most of two coordinators for follow-up and catch every urgent request within minutes.',
    dataNeeded:'Past tickets with their assignments; access to the inbox and the ticketing system.'},
   {id:'B2', name:'Diagnose and assign to a technician or vendor', who:'Trade supervisors', volume:'40 a day', systems:'Ticketing, asset register, vendor contracts, manuals',
    notes:'A supervisor reads the ticket, checks the asset\u2019s history, decides whether it is an in-house job or a vendor call, and assigns it. Experienced supervisors recognise a failing compressor from the description; new ones open the manual.',
    pain:'Assignment depends on who is on shift. Repeat faults are not recognised as repeats.',
    expert:{shape:'suggest', shapeAlt:['decide'], input:'structured', inputAlt:['text'], rep:'high', repAlt:[], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'Choosing the right responder and likely fix from history: suggest and rank.', input:'Asset history and contracts (structured) plus the ticket text.', rep:'Every ticket.', stakes:'A wrong call means a wasted visit or a longer outage: medium.'},
    fit:{best:['recommend'], ok:['retrieve','classify','rules']},
    fitNotes:{recommend:'Rank likely causes and the right responder from the asset\u2019s history and similar tickets. The supervisor decides.', retrieve:'Workable: surface the asset\u2019s history and the manual page for this fault.', classify:'Workable for in-house versus vendor, but the richer value is the suggestion.', rules:'Workable for contract routing (this asset, this vendor). It does not learn from outcomes.', predict:'Forecasting failures is the next step. This one is about responding well.', agent:'Assigning is one click once the decision is made.'},
    poorNote:'This step is a decision helped by history. Pick the capability that prepares the decision.',
    expertPick:'recommend', expertWhy:'Decision support: likely fault, recent history and the contract responder in one view, with the supervisor assigning.',
    autoBest:'review', autoOk:['assist'], autoNote:'Medium stakes: routine assignments can follow the suggestion automatically; anything unusual goes to the supervisor.',
    discoveries:[{title:'History by asset', text:'The asset register is complete for critical equipment and patchy for everything else.', effect:'Start with critical assets, where the value is anyway.'},{title:'Manuals in a cupboard', text:'Vendor manuals are PDFs in a shared folder, some scanned.', effect:'Retrieval needs them indexed: a week of work.'}],
    expertFeas:'mid', expertValue:'mid', realityNote:'Solid and sensible, medium on both axes. Build toward it after triage is in place.',
    metric:'Repeat visits per hundred tickets, and time from ticket to assignment', guardrails:['logging','sampling','escalation'],
    valueHyp:'Cut repeat visits by a third and make assignment consistent across shifts.',
    dataNeeded:'Asset register, ticket history with outcomes, vendor contracts, manuals.'},
   {id:'B3', name:'Schedule preventive maintenance', who:'Planning coordinator', volume:'2,300 tasks a year across 1,900 assets', systems:'Spreadsheet, vendor calendars',
    notes:'Preventive tasks are planned in a spreadsheet by frequency: quarterly filter changes, annual inspections, statutory tests. The coordinator juggles technician availability, vendor windows, building events and the vault\u2019s access rules. Eighteen percent of critical equipment is overdue.',
    pain:'A spreadsheet holds the plan, and the plan holds the building.',
    expert:{shape:'allocate', shapeAlt:[], input:'structured', inputAlt:['tacit'], rep:'high', repAlt:[], stakes:'mid', stakesAlt:['high']},
    profileNotes:{shape:'Fitting thousands of tasks into limited people, windows and access rules: allocate and schedule.', input:'Task lists and calendars are structured. Many constraints are in the coordinator\u2019s head.', rep:'Thousands of tasks a year.', stakes:'Overdue maintenance on a chiller or a vault system is serious: medium to high.'},
    fit:{best:['optimize'], ok:['predict','rules']},
    fitNotes:{optimize:'Scheduling under constraints is optimisation. It is what maintenance planning systems do, and it predates generative AI.', predict:'Workable: condition data can move tasks earlier or later than the fixed frequency.', rules:'Workable: a properly configured maintenance system with due-date rules would already beat the spreadsheet.', draft:'Nothing to write.', converse:'Nobody needs to chat with the schedule.'},
    poorNote:'This step is a scheduling problem with constraints. Pick the capability that finds the best plan.',
    expertPick:'optimize', expertWhy:'A maintenance planning system with constraint-based scheduling, the constraints written down, and the coordinator adjusting the plan rather than building it.',
    autoBest:'review', autoOk:['auto'], autoNote:'Medium to high stakes: the system proposes the schedule, the coordinator reviews and publishes it.',
    discoveries:[{title:'Constraints in a head', text:'Access rules, vendor lead times and event blackouts are known to one person.', effect:'Capture the constraints first.'},{title:'A system exists', text:'The Bank owns a maintenance management system that was never fully configured.', effect:'Feasibility: configuration before anything new.'}],
    expertFeas:'mid', expertValue:'high', realityNote:'High value, with the overdue figure to prove it. Medium feasibility until the constraints are written down and the existing system is switched on.',
    metric:'Critical equipment overdue, and planner hours per week', guardrails:['logging','rollback','sampling'],
    valueHyp:'Bring critical-equipment overdue from 18% to under 5%.',
    dataNeeded:'Asset list with frequencies, technician and vendor calendars, event blackouts, access rules.'},
   {id:'B4', name:'Spot failures early from building sensors', who:'Building engineers', volume:'14,000 sensor points, continuous', systems:'Building management system',
    notes:'The building management system records temperatures, pressures and run hours for the plant and the data halls. Engineers watch dashboards and respond to alarms. Nobody looks at trends until something fails.',
    pain:'Failures are found by alarm, not by trend. A data-hall cooling failure last winter was visible in the data three days early.',
    expert:{shape:'check', shapeAlt:['predict'], input:'structured', inputAlt:[], rep:'high', repAlt:[], stakes:'high', stakesAlt:['mid']},
    profileNotes:{shape:'Noticing that a system is drifting from normal: check and flag, edging into prediction.', input:'Sensor time series: structured.', rep:'Continuous.', stakes:'Data halls and vault systems: high.'},
    fit:{best:['anomaly'], ok:['predict','rules']},
    fitNotes:{anomaly:'Detecting drift from normal across thousands of points is anomaly detection, and it finds the failures alarms find too late.', predict:'Workable next: estimate remaining life for the key assets once the anomaly signal is trusted.', rules:'Threshold alarms are rules and already exist. They miss slow drift by design.', draft:'Nothing to write.', vision:'Nothing to look at.'},
    poorNote:'This step is about noticing drift in data. Pick the capability that spots what does not fit.',
    expertPick:'anomaly', expertWhy:'Anomaly detection on the critical plant and data-hall systems, tuned with the engineers so the flags are worth investigating.',
    autoBest:'review', autoOk:['assist'], autoNote:'High stakes, but the action is a human investigation: flag automatically, respond by hand.',
    discoveries:[{title:'Two years of history', text:'The building management system holds two years of sensor history, exported nightly.', effect:'Data: ready.'},{title:'Alarm fatigue', text:'Engineers already receive 300 alarms a day, most of them noise.', effect:'Change: the flags must be fewer and better than the alarms, or they will be ignored.'}],
    expertFeas:'high', expertValue:'high', realityNote:'Quick win on the critical systems: the data exists, integration is an export, and the last failure made the case.',
    metric:'Unplanned outages on critical systems, and useful flags per hundred raised', guardrails:['threshold','escalation','sampling'],
    valueHyp:'Catch most critical failures days early and halve alarm noise.',
    dataNeeded:'Sensor history, past failure records, and engineers\u2019 time to tune the flags.'},
   {id:'B5', name:'Close out and reconcile vendor invoices', who:'Facilities finance', volume:'1,800 vendor invoices a year', systems:'Ticketing, procurement, email',
    notes:'When a vendor finishes, the ticket is closed and the invoice arrives by email weeks later. A coordinator matches the invoice to the ticket and the contract rate, queries any difference, and passes it to accounts payable.',
    pain:'A day a week on matching. Fifteen percent of invoices are queried; some have been paid twice.',
    expert:{shape:'check', shapeAlt:[], input:'text', inputAlt:['structured'], rep:'high', repAlt:[], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'Comparing the invoice to the ticket and the contract: check and flag.', input:'Invoice PDFs (text) against tickets and rates (structured).', rep:'Weekly, the same motion.', stakes:'Money, caught later: medium.'},
    fit:{best:['extract','rules'], ok:['anomaly','agent']},
    fitNotes:{extract:'Reading the invoice into fields is the first half; then a rule does the match.', rules:'Matching invoice to ticket to contract rate is deterministic once the fields exist.', anomaly:'Workable: duplicates and unusual amounts against history.', agent:'Workable later: extract, match, query the vendor, and pass to accounts payable with a person approving.', draft:'Nothing to write beyond a query template.', predict:'Nothing to forecast.'},
    poorNote:'This step reads a document and compares it to records. Pick the capability that reads, and let a rule compare.',
    expertPick:'extract', expertWhy:'Extraction of invoice fields, rule-based matching to ticket and contract, and anomaly flags for duplicates. The coordinator handles the queries.',
    autoBest:'review', autoOk:['auto'], autoNote:'Medium stakes: match automatically, review the exceptions.',
    discoveries:[{title:'Forty vendors', text:'Forty vendors send 90% of invoices, in forty layouts.', effect:'Extraction handles the variety; template OCR would not.'},{title:'Rates in contracts', text:'Contract rates are in PDF contracts, not in the procurement system.', effect:'Data: load the rates first.'}],
    expertFeas:'high', expertValue:'low', realityNote:'Easy and cheap, but the prize is a day a week. A fill-in, best done together with the Bank-wide accounts payable process.',
    metric:'Coordinator hours on matching, and duplicate payments', guardrails:['threshold','logging','rollback'],
    valueHyp:'Cut matching to an hour a week and end duplicate payments.',
    dataNeeded:'Past invoices with their tickets, contract rates, procurement records.'},
  ]},
 C:{ id:'C', name:'Benefits inquiries & enrolment', fn:'Benefits organization', fnId:'benefits',
  intro:'Every autumn, 6,000 questions in five weeks, most of them the same forty. Year round, 9,000 documents to check and a queue of leave requests. Thirty-two people, 2,400 employees, 3,800 retirees, and information that must be handled with care. Walk the process.',
  steps:[
   {id:'C1', name:'Answer benefits questions', who:'Benefits counsellors', volume:'6,000 in enrolment season; 900 a month otherwise', systems:'Email, phone, plan documents, HR system',
    notes:'Employees ask which plan covers a procedure, what a change in family status means, what a contribution will cost. Counsellors look in the plan documents and the employee\u2019s record, then answer by email or phone. The same forty questions make up most of the season.',
    pain:'Eleven minutes on average, a three-day queue at peak, and inconsistent answers between counsellors.',
    expert:{shape:'lookup', shapeAlt:[], input:'text', inputAlt:['structured'], rep:'high', repAlt:[], stakes:'mid', stakesAlt:['low']},
    profileNotes:{shape:'Finding the answer in the plan and the record: look up and answer.', input:'Plan documents (text) and the employee record (structured).', rep:'Thousands, and the same forty questions.', stakes:'A wrong answer about coverage costs an employee money and trust: medium.'},
    fit:{best:['retrieve','converse'], ok:['draft','fix','classify']},
    fitNotes:{retrieve:'Retrieval over the plan documents, with the answer grounded and cited, is exactly the tool for forty repeated questions.', converse:'A conversational assistant on the benefits portal, answering from the same documents and handing off to a counsellor, removes the queue.', draft:'Workable with the facts retrieved first. A confident wrong answer about coverage is worse than a slow one.', fix:'Workable: a good FAQ and a decision guide would answer half the season on their own.', classify:'Workable for routing the unusual questions to the right specialist.', agent:'Answering a question does not need an agent.'},
    poorNote:'This step finds an answer that already exists in the plan. Pick the capability that finds and answers.',
    expertPick:'retrieve', expertWhy:'Retrieval over the plan documents, first as a counsellor tool, then as a self-service assistant with a clear path to a person. Answers cite the plan section.',
    autoBest:'review', autoOk:['assist','auto'], autoNote:'Medium stakes: counsellors send the drafted answers first; general plan questions can move to self-service once accuracy is proven. Anything about an individual\u2019s own claim stays with a person.',
    discoveries:[{title:'Plan documents are current', text:'Plan documents are updated every year and already published on the intranet.', effect:'Data: ready.'},{title:'The individual questions', text:'About 30% of questions need the employee\u2019s own record, which is protected information.', effect:'Risk: separate general plan questions from individual ones. The second set needs stricter handling.'}],
    expertFeas:'high', expertValue:'high', realityNote:'Quick win for the general questions. Individual questions come later, with proper controls.',
    metric:'Minutes per question, queue length in enrolment season, and answer consistency on audit', guardrails:['privacy','escalation','sampling'],
    valueHyp:'Cut the season queue from three days to same-day and make answers consistent.',
    dataNeeded:'Plan documents, past questions with counsellor answers, the portal.'},
   {id:'C2', name:'Verify eligibility documents', who:'Benefits specialists', volume:'9,000 documents a year', systems:'Upload portal, email, scanner, HR system',
    notes:'Marriage certificates, birth certificates, proof of coverage, leave forms: employees send them by upload, email or paper. A specialist checks each one is the right document, legible, and matches the request, then updates the record. Turnaround is eleven days.',
    pain:'Eleven days for a check that takes four minutes once the document is in front of someone.',
    expert:{shape:'extract', shapeAlt:['check'], input:'media', inputAlt:['text'], rep:'high', repAlt:[], stakes:'mid', stakesAlt:['high']},
    profileNotes:{shape:'Reading what the document is and what it says, then checking it against the request: extraction feeding a check.', input:'Scans and phone photos of certificates: images more than text.', rep:'Nine thousand a year.', stakes:'Personal and family information, and eligibility decisions: medium to high.'},
    fit:{best:['extract'], ok:['vision','rules','agent']},
    fitNotes:{extract:'Document extraction identifies the document type, reads names and dates, and checks legibility. A rule then compares against the request.', vision:'Workable, but document extraction already includes reading scans. A separate vision project is not needed.', rules:'Workable for the comparison once the fields are read.', agent:'Workable later: read, compare, update the record, and ask the employee for a better copy when needed.', classify:'Knowing which document it is is part of the work, not all of it.', converse:'Nobody is conversing.'},
    poorNote:'This step reads a document and compares it to a request. Pick the capability that reads documents.',
    expertPick:'extract', expertWhy:'Extraction with document-type detection and legibility checks, a rule for the match, and a specialist reviewing anything uncertain.',
    autoBest:'review', autoOk:['assist'], autoNote:'Medium to high stakes with personal data: review what the tool is unsure of, and keep a person on every decision that denies eligibility.',
    discoveries:[{title:'Photos of certificates', text:'Most documents arrive as phone photos: skewed, shadowed, sometimes cropped.', effect:'Extraction copes, with lower confidence. Ask for a better photo automatically.'},{title:'Protected information', text:'These documents are protected personal information under the Bank\u2019s policy. Storage and access are audited.', effect:'Risk: the tool must run inside the approved environment with full logging.'}],
    expertFeas:'mid', expertValue:'high', realityNote:'High value against the eleven-day figure. Medium feasibility because of the handling requirements: a strategic bet with a clear path.',
    metric:'Days to verify, and documents returned for resubmission', guardrails:['privacy','threshold','logging'],
    valueHyp:'Cut turnaround from eleven days to two.',
    dataNeeded:'Past documents with their decisions, the request records, an approved environment.'},
   {id:'C3', name:'Process enrolment changes', who:'Benefits specialists', volume:'3,200 changes in season; 400 a month otherwise', systems:'Enrolment portal, HR system, carrier files',
    notes:'An employee\u2019s election in the portal must be checked against eligibility rules, entered into the HR system, and sent to the insurance carriers in their file formats. Most changes are routine. A few break a rule the portal did not catch.',
    pain:'Re-keying between systems. Carrier rejections come back two weeks later.',
    expert:{shape:'coordinate', shapeAlt:['check'], input:'structured', inputAlt:[], rep:'high', repAlt:[], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'Moving a validated election between three systems: coordinate and update, with a rule check.', input:'Portal elections and HR records: structured.', rep:'Thousands, nearly identical.', stakes:'Wrong coverage for an employee: medium.'},
    fit:{best:['rules'], ok:['anomaly','agent','fix']},
    fitNotes:{rules:'Validating against eligibility rules and passing elections between systems is deterministic. The portal and the HR system can be integrated; no AI is needed.', anomaly:'Workable for the elections that look unusual against the employee\u2019s history.', agent:'Workable but oversized: an agent re-keying between systems preserves the gap that should be closed.', fix:'The portal should validate the rules the carriers reject on. Fix the form.', extract:'The data is already structured.', predict:'Nothing to forecast.'},
    poorNote:'This step moves structured data between systems by rule. Ask what a rule and an integration would do before asking about AI.',
    expertPick:'rules', expertWhy:'Integrate the portal, the HR system and the carrier files, and put the carriers\u2019 rules into the portal. This is engineering, not AI.',
    autoBest:'auto', autoOk:['review'], autoNote:'Low to medium stakes, deterministic: fully automatic with exception reports.',
    discoveries:[{title:'Carrier rules are known', text:'Carrier rejection reasons fall into twelve categories, all rule-based.', effect:'Put the rules in the portal.'},{title:'Integration exists elsewhere', text:'The HR system has a carrier-file module the Bank never licensed.', effect:'Feasibility: a licence and configuration.'}],
    expertFeas:'high', expertValue:'mid', realityNote:'A quick win that is not an AI project. Do it, and do not call it AI.',
    metric:'Carrier rejections, and specialist hours on re-keying', guardrails:['logging','rollback','sampling'],
    valueHyp:'End re-keying and cut carrier rejections by 80%.',
    dataNeeded:'Portal, HR system, carrier specifications, rejection history.'},
   {id:'C4', name:'Administer leave requests', who:'Leave specialists', volume:'1,400 leave cases a year', systems:'Email, HR system, certifications',
    notes:'An employee requests leave. The specialist determines which policies and legal entitlements apply, what documentation is needed and the dates, then tracks the case through return to work. Cases involve medical information and sometimes disputes.',
    pain:'Two hours of specialist time to set up a case, and uneven consistency between specialists.',
    expert:{shape:'decide', shapeAlt:['lookup'], input:'text', inputAlt:['structured'], rep:'mid', repAlt:[], stakes:'high', stakesAlt:[]},
    profileNotes:{shape:'Determining entitlement and documentation is a judgment call with legal weight: judge and decide, with lookup underneath.', input:'Emails and certifications (text) plus the employee record.', rep:'Fourteen hundred a year, each different.', stakes:'Legal entitlements and medical information: high.'},
    fit:{best:['recommend','retrieve'], ok:['summarize','draft']},
    fitNotes:{recommend:'Decision support: propose the applicable policies, entitlements and required documents with the reasoning, for the specialist to confirm.', retrieve:'Surface the policy and precedent for this situation from the leave handbook and past cases.', summarize:'Workable: a case summary at each handover.', draft:'Workable for the standard letters once the decision is made.', agent:'Automating leave decisions is the wrong place to start: legal weight, medical information, disputes.', rules:'Some entitlements are rule-based. The interactions between them are where specialists earn their pay.'},
    poorNote:'This is a judgment call with legal weight. AI earns its place by preparing the decision, not making it.',
    expertPick:'recommend', expertWhy:'Assist mode: policies, entitlements and documents proposed with reasons and sources. The specialist decides and the decision is logged.',
    autoBest:'assist', autoOk:[], autoNote:'High stakes and medical information: a person decides every case.',
    discoveries:[{title:'Handbook and precedent', text:'The leave handbook is thorough. Past case decisions are in emails.', effect:'Capture decisions in a structured log to make consistency measurable.'},{title:'Medical information', text:'Certifications contain medical information with the strictest handling rules in the Bank.', effect:'Risk: the tool must not see the medical detail. Work from the certification status only.'}],
    expertFeas:'low', expertValue:'mid', realityNote:'Sensible, sensitive and slow to land. Medium value and low feasibility until case decisions are logged and the medical boundary is designed. Park it, then build toward it.',
    metric:'Set-up hours per case, and consistency of determinations on audit', guardrails:['privacy','logging','escalation'],
    valueHyp:'Halve set-up time and make determinations consistent.',
    dataNeeded:'Leave handbook, a structured case log, employee records without medical detail.'},
   {id:'C5', name:'Reconcile carrier invoices to enrolment', who:'Benefits finance', volume:'14 carriers, monthly', systems:'Carrier files, enrolment records',
    notes:'Each month the insurance carriers bill for everyone enrolled. An analyst compares the bill to the Bank\u2019s enrolment records, finds people billed who left or changed plans, and disputes the difference.',
    pain:'Three days a month. Overbilling recovered last year was $410,000, found late.',
    expert:{shape:'check', shapeAlt:[], input:'structured', inputAlt:['text'], rep:'mid', repAlt:['high'], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'Comparing bills to records and flagging differences: check and flag.', input:'Carrier files and enrolment records: structured, with two PDF stragglers.', rep:'Monthly, fourteen times.', stakes:'Money, recoverable: medium.'},
    fit:{best:['rules'], ok:['anomaly','extract']},
    fitNotes:{rules:'Matching bills to enrolment is deterministic and the carrier files are structured. A rule does this monthly in minutes.', anomaly:'Workable for the patterns rules do not anticipate, such as a carrier billing a plan the Bank does not offer.', extract:'Workable for the two carriers that still send PDF bills.', predict:'Nothing to forecast.', agent:'Disputing is a template email once the match is done.'},
    poorNote:'Structured records are being compared. That is a rule.',
    expertPick:'rules', expertWhy:'Rule-based reconciliation on the carrier files, anomaly flags for the unexpected, and extraction only for the PDF stragglers.',
    autoBest:'auto', autoOk:['review'], autoNote:'Deterministic matching runs automatically; an analyst reviews the differences.',
    discoveries:[{title:'Structured files', text:'Twelve of fourteen carriers send structured files. Two send PDFs.', effect:'Rules for twelve, extraction for two.'},{title:'Late discovery', text:'Overbilling is found months later because reconciliation is quarterly in practice.', effect:'Value: monthly automatic reconciliation recovers faster.'}],
    expertFeas:'high', expertValue:'mid', realityNote:'A quick win, mostly rules. Do it this quarter.',
    metric:'Analyst days per month, and overbilling recovered within 30 days', guardrails:['logging','sampling','rollback'],
    valueHyp:'Cut reconciliation to half a day and recover overbilling within the month.',
    dataNeeded:'Carrier files, enrolment records, dispute history.'},
  ]},
 D:{ id:'D', name:'Visitor & delivery screening', fn:'Law enforcement', fnId:'police',
  intro:'Three hundred and eighty thousand visitors and deliveries a year through three lobbies and two loading docks. Hosts pre-register by email in whatever format they like; officers re-key at the desk, check the lists, screen the person and the package, and write up anything unusual. Walk the process.',
  steps:[
   {id:'D1', name:'Pre-register visitors from host requests', who:'Desk officers', volume:'1,200 registrations a day', systems:'Email, visitor management system',
    notes:'Hosts email the desk with visitor names, companies, dates and purposes, in 900 different styles: a table, a sentence, a forwarded thread. An officer re-keys each into the visitor system and emails the host if something is missing.',
    pain:'Four officer-hours a day of typing. Missing details are discovered when the visitor is already at the desk.',
    expert:{shape:'extract', shapeAlt:[], input:'text', inputAlt:[], rep:'high', repAlt:[], stakes:'low', stakesAlt:['mid']},
    profileNotes:{shape:'Pulling names, dates and purposes out of emails into fields: extraction.', input:'Emails in every style: text.', rep:'Twelve hundred a day.', stakes:'A wrong name is caught at the desk: low, leaning medium.'},
    fit:{best:['extract','fix'], ok:['agent','rules']},
    fitNotes:{extract:'Reading free-form host emails into visitor records is extraction, and it copes with the 900 styles.', fix:'A host self-registration form, made the default, removes most of the email. Try that first.', agent:'Workable: extract, create the record, and ask the host for missing details automatically.', rules:'A form is a rule; an email is not. Rules alone cannot read the thread.', classify:'Knowing it is a registration is not the problem.', converse:'A conversational registration could work. The form is simpler.'},
    poorNote:'This step turns emails into records. Pick the capability that reads, or the fix that makes reading unnecessary.',
    expertPick:'fix', expertWhy:'A host form as the default removes most of the typing. Extraction handles the emails that still come, and asks hosts for what is missing.',
    autoBest:'auto', autoOk:['review'], autoNote:'Low stakes and verified at the desk anyway: automatic, with the desk as the check.',
    discoveries:[{title:'A form exists', text:'The visitor system has a host portal. Eight percent of hosts use it, because it needs a separate login.', effect:'Fix the login, then extract the rest.'},{title:'Names must match identity', text:'Registration names are checked against identity documents at the desk, so errors are caught before entry.', effect:'Stakes stay low because the desk is the control.'}],
    expertFeas:'high', expertValue:'mid', realityNote:'Quick win, and mostly a process fix. Four officer-hours a day back on the floor.',
    metric:'Officer hours on registration, and visitors held at the desk for missing details', guardrails:['threshold','logging','escalation'],
    valueHyp:'Cut registration typing by 80% and desk holds by half.',
    dataNeeded:'Past host emails with their records, the host portal, the visitor system.'},
   {id:'D2', name:'Screen visitors against lists and access rules', who:'Desk officers', volume:'1,200 a day', systems:'Visitor system, internal and external lists, identity checks',
    notes:'At the desk the officer checks the visitor\u2019s identity document, matches the name against internal and external lists, confirms the host and the areas the visitor may enter, and issues a badge. Most checks take a minute. A hit or a mismatch takes a supervisor.',
    pain:'Queues at half past eight. Near-matches on common names take time. The rules for area access differ by building.',
    expert:{shape:'check', shapeAlt:[], input:'structured', inputAlt:['media'], rep:'high', repAlt:[], stakes:'high', stakesAlt:[]},
    profileNotes:{shape:'Comparing a person against lists and rules: check and flag.', input:'Identity data and lists (structured), with the document itself as an image.', rep:'Twelve hundred a day.', stakes:'The perimeter of the building: high.'},
    fit:{best:['rules','anomaly'], ok:['extract','vision','recommend']},
    fitNotes:{rules:'List matching and access rules are deterministic and should run in the visitor system automatically. The officer\u2019s judgment belongs on the hits.', anomaly:'Workable for the patterns rules miss: unusual visit frequency, a host who registers many strangers, a badge used oddly.', extract:'Workable for reading the identity document into the check.', vision:'Workable for document authenticity checks, a specialist product area with its own rules.', recommend:'Workable for near-matches: rank likelihood so the supervisor decides faster.', agent:'Nobody should let a tool admit a visitor on its own.', converse:'Nobody is conversing at the desk.'},
    poorNote:'This step checks a person against lists and rules. Pick the capability that checks, and keep the officer on the hits.',
    expertPick:'rules', expertWhy:'Automate the deterministic checks in the visitor system, add anomaly flags for unusual patterns, and keep an officer deciding every hit and near-match.',
    autoBest:'review', autoOk:['assist'], autoNote:'High stakes at the edges: automate the clear passes, route every hit and near-match to an officer. Never fully automate admission.',
    discoveries:[{title:'Lists update nightly', text:'Internal and external lists are refreshed nightly and are already in the visitor system.', effect:'Data: ready.'},{title:'Three rule books', text:'Area access rules differ by building and live in three documents.', effect:'Change: harmonise the rules, then encode them.'}],
    expertFeas:'high', expertValue:'high', realityNote:'Quick win on the deterministic checks. The judgment stays exactly where it is, and the morning queue is the metric.',
    metric:'Average screening time, and hits resolved within five minutes', guardrails:['logging','escalation','sampling'],
    valueHyp:'Halve the morning queue without lowering a single standard.',
    dataNeeded:'Visitor system, list feeds, the three access rule books, past hit resolutions.'},
   {id:'D3', name:'Screen deliveries and mail', who:'Dock officers', volume:'600 packages and 4,000 mail items a day', systems:'X-ray, trace detection, delivery logs',
    notes:'Everything arriving at the docks is x-rayed and, where indicated, swabbed. Officers read the images, compare against the expected-delivery log, and clear or hold. Two officers per lane, four lanes, all day.',
    pain:'Fatigue on the image screen after two hours. Expected-delivery logs are kept by email and printed each morning.',
    expert:{shape:'check', shapeAlt:[], input:'media', inputAlt:[], rep:'high', repAlt:[], stakes:'high', stakesAlt:[]},
    profileNotes:{shape:'Deciding whether an image shows something that should not be there: check and flag.', input:'X-ray images: media.', rep:'Thousands a day.', stakes:'The building\u2019s safety: high.'},
    fit:{best:['vision'], ok:['rules','anomaly']},
    fitNotes:{vision:'Image analysis that highlights regions of concern for the officer is a mature, regulated product area. The officer still decides.', rules:'Workable for matching packages to the expected-delivery log.', anomaly:'Workable for unexpected patterns in deliveries. It does not read images.', extract:'Nothing to extract from an x-ray.', converse:'No.'},
    poorNote:'This step reads images for threats. Pick the capability that sees, and keep the officer deciding.',
    expertPick:'vision', expertWhy:'Certified image-analysis assistance on the x-ray lanes that highlights concerns, with the officer clearing every item. Plus a proper expected-delivery register.',
    autoBest:'assist', autoOk:[], autoNote:'High stakes: the tool highlights, the officer decides every item.',
    discoveries:[{title:'Certified products only', text:'Screening equipment and its software must be certified. The choice is among certified vendors, not general-purpose tools.', effect:'Feasibility: a procurement of certified equipment, not a software pilot.'},{title:'The log by email', text:'Expected deliveries are emailed by hosts and printed each morning.', effect:'Fix first: a delivery register the dock can search.'}],
    expertFeas:'low', expertValue:'mid', realityNote:'Medium value, low feasibility for a discovery programme: it is a certified-equipment procurement. Park it here, and fix the delivery log now.',
    metric:'Items held for secondary screening, and officer fatigue rotations', guardrails:['escalation','logging','sampling'],
    valueHyp:'Reduce missed anomalies under fatigue and shorten secondary screening.',
    dataNeeded:'A certified-equipment evaluation and the delivery register.'},
   {id:'D4', name:'Write and review incident reports', who:'Officers and supervisors', volume:'35 reports a day across three buildings', systems:'Notebooks, recorders, report system',
    notes:'After a shift, officers type up incidents from notes: a dispute at the desk, a door alarm, a medical assist. Supervisors review each report for completeness and classification, and send anything serious upward. Two hours of supervisor time a day, per building.',
    pain:'Reports are written late from memory, classification is inconsistent, and supervisors read everything.',
    expert:{shape:'draft', shapeAlt:['route'], input:'text', inputAlt:['media'], rep:'high', repAlt:[], stakes:'mid', stakesAlt:['high']},
    profileNotes:{shape:'Turning notes into a structured report: draft, then sort by seriousness.', input:'Handwritten notes and dictation: text, some audio.', rep:'Thirty-five a day.', stakes:'Reports can become evidence: medium, leaning high.'},
    fit:{best:['draft','classify'], ok:['speech','summarize']},
    fitNotes:{draft:'A structured report drafted from the officer\u2019s notes or dictation, in the required format, for the officer to correct and sign.', classify:'Classifying seriousness and type consistently, so supervisors read the serious ones first.', speech:'Workable: dictation at the scene beats notes typed hours later.', summarize:'Workable for the supervisor\u2019s daily digest.', agent:'Nothing to coordinate.', predict:'Nothing to forecast.'},
    poorNote:'This step writes and sorts reports. Pick the capability that drafts, and keep the officer signing.',
    expertPick:'draft', expertWhy:'Dictate at the scene, draft the report in format, classify it, and have the officer sign it. Supervisors review a prioritised queue.',
    autoBest:'assist', autoOk:['review'], autoNote:'Medium to high stakes because reports may become evidence: the officer owns every word and signs it.',
    discoveries:[{title:'Recorders exist', text:'Officers already carry recorders. Consent and retention rules are in place.', effect:'Data: ready for dictation.'},{title:'Evidence standards', text:'Reports may be used in proceedings. The drafting tool\u2019s role must be documented.', effect:'Risk: log the tool\u2019s contribution and the officer\u2019s edits.'}],
    expertFeas:'mid', expertValue:'mid', realityNote:'Solid, medium on both axes. Build toward it with the evidence question answered first.',
    metric:'Minutes from incident to signed report, and reports returned for correction', guardrails:['logging','privacy','escalation'],
    valueHyp:'Halve report time and make classification consistent across buildings.',
    dataNeeded:'Past reports with classifications, the recorders, the report format.'},
   {id:'D5', name:'Schedule patrols and shifts', who:'Shift sergeants', volume:'190 officers, 3 buildings, around the clock', systems:'Spreadsheet, leave system, events calendar',
    notes:'Sergeants build the roster in a spreadsheet: coverage minimums per post, certifications, leave, overtime rules, training days and the events calendar. A change on Monday cascades through the week by phone.',
    pain:'A sergeant-day a week per building, and overtime 14% above budget.',
    expert:{shape:'allocate', shapeAlt:[], input:'structured', inputAlt:['tacit'], rep:'high', repAlt:[], stakes:'mid', stakesAlt:[]},
    profileNotes:{shape:'Fitting people into posts under rules: allocate and schedule.', input:'Posts, certifications and leave are structured. Preferences and trade-offs are tacit.', rep:'Every week.', stakes:'Coverage gaps and overtime: medium.'},
    fit:{best:['optimize'], ok:['rules','predict']},
    fitNotes:{optimize:'Rostering under constraints is optimisation, well established in policing and hospitals.', rules:'Workable: a rostering system with rule checks would already beat the spreadsheet.', predict:'Workable: forecast demand from the events calendar and absence patterns.', draft:'Nothing to write.', converse:'Nobody needs to chat with the roster.'},
    poorNote:'This step is a scheduling problem under rules. Pick the capability that finds the best plan.',
    expertPick:'optimize', expertWhy:'Constraint-based rostering with sergeants adjusting the proposal, overtime rules encoded, and changes cascading automatically.',
    autoBest:'review', autoOk:['auto'], autoNote:'Medium stakes: the system proposes, the sergeant publishes.',
    discoveries:[{title:'Rules are written', text:'Coverage minimums, certification and overtime rules are in the collective agreement and policy: written and precise.', effect:'Data: the constraints are already captured.'},{title:'Fairness matters', text:'Officers care about the fair distribution of nights and overtime. The roster is a trust issue.', effect:'Change: make the fairness rules explicit and visible.'}],
    expertFeas:'high', expertValue:'high', realityNote:'Quick win: written rules, a clear cost, a mature technique. The fairness rules are the adoption key.',
    metric:'Overtime against budget, and sergeant hours on rostering', guardrails:['logging','rollback','sampling'],
    valueHyp:'Bring overtime back to budget and return a day a week to each sergeant.',
    dataNeeded:'Posts and minimums, certifications, leave, the events calendar, the agreement rules.'},
  ]},
};

/* ---------- Trail events: the traps ---------- */
const EVENTS = {
  E1:{title:'The demo', text:'A senior leader saw a vendor demo last week and now wants "a chatbot for the Bank" live before the next leadership meeting. Your sponsor asks you to make it happen.',
    opts:[{t:'Start scoping the chatbot. It is what leadership asked for.', s:0, fb:'A chatbot is a capability, not a use case. Without a process and a step, you will build a front door to nothing in particular.'},
          {t:'Ask which process it would improve and which step, then evaluate a conversational assistant alongside the other capability types for that step.', s:2, fb:'Tools are answers. You do not have a question yet. Anchor the request to a step in a process and the right capability may or may not be a chatbot.'},
          {t:'Push back: chatbots do not work.', s:0, fb:'Some do, in the right place. Dismissing the tool is the same mistake as worshipping it: it skips the work.'}]},
  E2:{title:'The brand name', text:'A colleague insists the Bank needs one specific, well-known product. "Every other institution uses it. Just buy it and move on."',
    opts:[{t:'Buy it. A known brand is the safe choice.', s:0, fb:'Brands change, get acquired and get outrun. Buying before you know what the step needs makes the tool the requirement.'},
          {t:'Write down the capability the step needs (what it must read, decide or produce, at what accuracy, volume and sensitivity), then evaluate any option, including that one, against it.', s:2, fb:'The capability requirement outlives any vendor. It also makes the comparison honest, and it is the thing you can hand to procurement.'},
          {t:'Ban vendors and build everything in-house.', s:0, fb:'Building is a valid option for some capabilities, but deciding it before you know the requirement is the same error in a different jacket.'}]},
  E7:{title:'The paste', text:'An economist, trying to save an afternoon, is about to paste a draft section of the briefing memo into a public AI tool to tighten the prose.',
    opts:[{t:'Let it go. It is only a draft, and the tool is good.', s:0, fb:'A draft of the most sensitive document in the building just left the building. Sensitivity attaches to the information, not to the version.'},
          {t:'Stop it, and treat it as a signal: classify the information first, and give people an approved environment for exactly this kind of help.', s:2, fb:'People route around missing tools. Decide what may leave, what may not, and what may never be seen by a tool at all, then provide an inside option, or the paste happens again with nobody watching.'},
          {t:'Ban AI tools for economists.', s:1, fb:'It closes one door and teaches nothing. The need is real; the answer is an approved way to meet it.'}]},
  E3:{title:'The workaround', text:'Digging into a step, you find it exists because two systems do not share a field. Somebody re-keys the same information every day, and has for six years.',
    opts:[{t:'Automate the re-keying with an agent. Fast relief.', s:1, fb:'It works, and sometimes it is the pragmatic bridge. But you have now bought a tool to preserve a defect. Note the real fix and a date to make it.'},
          {t:'Fix the integration or the form so the field flows through, then see what work is left.', s:2, fb:'Remove the cause and the step may vanish. Automating a broken process only makes it break faster.'},
          {t:'Add a second person to check the re-keying.', s:0, fb:'Now two people preserve the defect.'}]},
  E4:{title:'The spreadsheet archipelago', text:'The "data" a use case depends on turns out to live in fourteen personal spreadsheets with different column names, two of which belong to someone who retired in March.',
    opts:[{t:'Feed the spreadsheets to a model and see what comes out.', s:0, fb:'What comes out will look plausible and be wrong in ways nobody can check. Uncaptured or inconsistent data is a step-zero problem, not something a model fixes.'},
          {t:'Treat data capture as step zero: agree where the data lands and in what shape, then pilot on the subset that is already clean.', s:2, fb:'Most use cases that fail, fail here. Capturing the data properly is unglamorous, and it is the work.'},
          {t:'Drop the use case.', s:1, fb:'Sometimes right, but check the size of the prize first. If the value is large, a data-capture project is the first phase, not a reason to stop.'}]},
  E5:{title:'The team meeting', text:'You present the idea to the team whose work it touches. The room goes quiet. Someone asks whether this means job cuts.',
    opts:[{t:'Reassure them that nothing will change.', s:0, fb:'Something will change, or why do it? People can tell. Vague reassurance costs you the trust you need for the pilot.'},
          {t:'Be specific: which tasks change, what they will do with the time, how they will be involved in testing, and how errors will be caught.', s:2, fb:'Specifics are respect. The people who do the work today are also the only ones who can tell you when the tool is wrong.'},
          {t:'Present it to their manager only, next time.', s:0, fb:'The tool will be judged by the people who use it. Cutting them out delays the conversation and worsens it.'}]},
  E6:{title:'The metric', text:'Your sponsor asks the question that decides whether this becomes a programme or a slide: "How will we know it worked?"',
    opts:[{t:'Count the AI features we ship this year.', s:0, fb:'Activity, not outcome. Shipping features is easy. Changing the step is the point.'},
          {t:'Measure the step now (time, error rate, cost per item, cycle time) and compare the pilot against that baseline.', s:2, fb:'A baseline measured before the pilot is the difference between a result and an anecdote.'},
          {t:'Run a satisfaction survey after launch.', s:1, fb:'Useful alongside a baseline, not instead of one. Satisfaction can rise while the work gets worse.'}]},
};
const EVENT_TRIGGERS = {afterTerrain:'E1', afterStep2:'E2', afterStep3:'E7', afterStep4:'E3', beforeReality:'E4', beforeCanvas:'E5', beforeDebrief:'E6'};

/* ---------- Debrief content ---------- */
const TAKEAWAYS = [
  {h:'Start from the work, not the tool', d:'A capability is an answer. Find the question first: a process, a step, a measurable pain.'},
  {h:'A hotspot has four ingredients', d:'Volume, repetition, a pain you can measure, and inputs that are already captured. Pain alone is not enough.'},
  {h:'The shape of the work points to the capability', d:'Reading, sorting, looking up, writing, condensing, estimating, checking, ranking, allocating, deciding, chasing. Each has a capability type behind it. Brands come last.'},
  {h:'Ask what a rule would do first', d:'If the logic can be written down, a rule or your existing system is cheaper and more predictable. If the step exists because of a broken handoff, fix the handoff.'},
  {h:'Match autonomy to stakes', d:'Assist when a person must own the call. Review when the routine is safe and the exceptions are not. Automate when errors are cheap and reversible.'},
  {h:'Classify the information before you connect the tool', d:'What may leave the building, what may not, and what may never be seen by a tool at all. Decide it once, write it down, and give people an approved way to get the help they want.'},
  {h:'Reality check before you pitch', d:'Data readiness, risk, change effort and integration on one axis; value on the other. Quick wins build the trust that strategic bets need.'},
  {h:'Measure the baseline before the pilot', d:'Time, error rate, cost per item, cycle time. Without a baseline you will have an anecdote, not a result.'},
];
const RANKS = [
  {min:0,   name:'Day tripper',      d:'You saw the terrain. Next time, spend longer at each step before reaching for the toolkit.'},
  {min:40,  name:'Trail scout',      d:'You can find the hotspots and name most of the work. Practise the matching and the reality check.'},
  {min:60,  name:'Cartographer',     d:'You dissect processes well and match capabilities sensibly. The reality check is where the last points live.'},
  {min:80,  name:'Expedition lead',  d:'You start from the work, match the capability, size the autonomy and check reality. Take a team through it.'},
];
const DISCUSS = {
  terrain:'Which signal is evidence of a hotspot, and which is just loud? Agree the three before you lock them in.',
  profile:'Where do you disagree about the shape of this work? The disagreement usually reveals two steps hiding in one.',
  match:'Would a rule do this? What makes it need AI? Who is accountable if it is wrong, and what information does the tool get to see?',
  reality:'What would you need to see to move this one to the right on the map? Who owns that?',
  canvas:'Who will measure the baseline, and by when?',
};
